### ISSUE TITLE
Non-standard meta tag

### ISSUE THREAD

**Issue by oliverjam** [fac18/hussh#35]
https://github.com/fac18/hussh/blob/b7dfef592e7ea49f93ccbd0fe5f883e7fd068749/index.html#L7

I'm not sure what this meta tag is doing, but there is a standardised list of allowed values for `name` that you can see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Attributes

**Comment by marialani** [comment]
When researching the naming conventions we had mistakenly looked into conventions related to a different tag.
We have resolved this by reverting to the default properties for the meta tag.
